- purl: pkg:pypi/ansible@2.8.15
  affected_by_advisories:
    - pypa_importer_v2/PYSEC-2020-209
    - pypa_importer_v2/PYSEC-2020-220
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2020-3
    - pypa_importer_v2/PYSEC-2021-1
    - pypa_importer_v2/PYSEC-2021-105
    - pypa_importer_v2/PYSEC-2021-106
    - pypa_importer_v2/PYSEC-2021-124
    - pypa_importer_v2/PYSEC-2021-125
    - pypa_importer_v2/PYSEC-2021-126
    - pypa_importer_v2/PYSEC-2021-358
    - pypa_importer_v2/PYSEC-2022-164
    - pysec_importer_v2/PYSEC-2020-209
    - pysec_importer_v2/PYSEC-2020-220
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2020-3
    - pysec_importer_v2/PYSEC-2021-1
    - pysec_importer_v2/PYSEC-2021-105
    - pysec_importer_v2/PYSEC-2021-106
    - pysec_importer_v2/PYSEC-2021-124
    - pysec_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2021-126
    - pysec_importer_v2/PYSEC-2021-358
  fixing_advisories:
    - github_osv_importer_v2/GHSA-m429-fhmv-c6q2
    - gitlab_importer_v2/pypi/ansible/CVE-2020-14365
